/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CashDrawerRouteImport } from './routes/cash-drawer'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryProductIdRouteImport } from './routes/inventory.$productId'
import { Route as InventoryImportRouteImport } from './routes/inventory.import'
import { Route as InventoryNewRouteImport } from './routes/inventory.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CashDrawerRoute = CashDrawerRouteImport.update({
  id: '/cash-drawer',
  path: '/cash-drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductIdRoute = InventoryProductIdRouteImport.update({
  id: '/inventory/$productId',
  path: '/inventory/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryImportRoute = InventoryImportRouteImport.update({
  id: '/inventory/import',
  path: '/inventory/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash-drawer': typeof CashDrawerRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/more': typeof MoreRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/inventory/$productId': typeof InventoryProductIdRoute
  '/inventory/import': typeof InventoryImportRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash-drawer': typeof CashDrawerRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/more': typeof MoreRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/inventory/$productId': typeof InventoryProductIdRoute
  '/inventory/import': typeof InventoryImportRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cash-drawer': typeof CashDrawerRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/more': typeof MoreRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/inventory/$productId': typeof InventoryProductIdRoute
  '/inventory/import': typeof InventoryImportRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cash-drawer'
    | '/customers'
    | '/expenses'
    | '/more'
    | '/purchases'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/staff'
    | '/inventory/$productId'
    | '/inventory/import'
    | '/inventory/new'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cash-drawer'
    | '/customers'
    | '/expenses'
    | '/more'
    | '/purchases'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/staff'
    | '/inventory/$productId'
    | '/inventory/import'
    | '/inventory/new'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cash-drawer'
    | '/customers'
    | '/expenses'
    | '/more'
    | '/purchases'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/staff'
    | '/inventory/$productId'
    | '/inventory/import'
    | '/inventory/new'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CashDrawerRoute: typeof CashDrawerRoute
  CustomersRoute: typeof CustomersRoute
  ExpensesRoute: typeof ExpensesRoute
  MoreRoute: typeof MoreRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  InventoryProductIdRoute: typeof InventoryProductIdRoute
  InventoryImportRoute: typeof InventoryImportRoute
  InventoryNewRoute: typeof InventoryNewRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-drawer': {
      id: '/cash-drawer'
      path: '/cash-drawer'
      fullPath: '/cash-drawer'
      preLoaderRoute: typeof CashDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$productId': {
      id: '/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof InventoryProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/import': {
      id: '/inventory/import'
      path: '/inventory/import'
      fullPath: '/inventory/import'
      preLoaderRoute: typeof InventoryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CashDrawerRoute: CashDrawerRoute,
  CustomersRoute: CustomersRoute,
  ExpensesRoute: ExpensesRoute,
  MoreRoute: MoreRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  InventoryProductIdRoute: InventoryProductIdRoute,
  InventoryImportRoute: InventoryImportRoute,
  InventoryNewRoute: InventoryNewRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
